name: Cache Theos
description: Caches Theos clone and iOS SDK

inputs:
  theos_commit:
    required: true
  sdk_version:
    required: false
    default: '18.6'

outputs:
  cache-hit:
    description: Whether Theos was restored from cache
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Restore Theos cache
      id: cache
      uses: actions/cache@v5.0.5
      with:
        path: ${{ github.workspace }}/theos
        key: theos-v2-${{ inputs.theos_commit }}-sdk${{ inputs.sdk_version }}

    - name: Clone Theos
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: git clone --quiet --depth=1 --recurse-submodules https://github.com/theos/theos.git ${{ github.workspace }}/theos

    - name: Set THEOS env
      shell: bash
      run: echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

    - name: Export THEOS path
      shell: bash
      run: echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV
